spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;mode=mysql
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    user:
      name: nhs0912
      password: nhs0912_oneGo

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:h2:~/test
    user: sa
    password:

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
      org.springframework: debug
  integration:
    management:
      default-logging-enabled: true
jwt:
  issuer: nhs0912@nate.com
  secret_key: onego-springboot
  token-validity-in-seconds: 28800 #8 hours
