create table if not exists refresh_token (
                                       id bigint generated by default as identity,
                                       member_id bigint not null,
                                       refresh_token varchar(1000) not null,
                                       created_date timestamp(6),
                                       primary key (id)
);
