create table if not exists team (
                                       id bigint generated by default as identity,
                                       code varchar(4) not null,
                                       name varchar(255),
                                       created_date timestamp(6),
                                       last_modified_date timestamp(6),
                                       primary key (id)
);