create table if not exists members (
                        id bigint generated by default as identity,
                        email varchar(255),
                        employee_id varchar(255) not null,
                        password varchar(255),
                        name varchar(255),
                        grade varchar(255),
                        role varchar(255),
                        status varchar(255),
                        team_id bigint,
                        created_date timestamp(6),
                        last_modified_date timestamp(6),
                        primary key (id)
);

alter table if exists members
    add constraint UK_mbmcqelty0fbrvxp1q58dn57t unique (email);

alter table if exists members
    add constraint UK_4rebv7u7h123c0kvaq3jv89ym unique (employee_id);