create table member (
                        id bigint generated by default as identity,
                        created_date timestamp(6),
                        last_modified_date timestamp(6),
                        email varchar(255),
                        employee_id varchar(255) not null,
                        grade varchar(255),
                        name varchar(255),
                        password varchar(255),
                        role varchar(255),
                        status varchar(255),
                        team_id bigint,
                        primary key (id)
)

create table refresh_token (
                               id bigint generated by default as identity,
                               member_id bigint not null,
                               refresh_token varchar(255) not null,
                               primary key (id)
)

create table team (
                      id bigint generated by default as identity,
                      created_date timestamp(6),
                      last_modified_date timestamp(6),
                      name varchar(255),
                      primary key (id)
)

alter table if exists member
    add constraint UK_mbmcqelty0fbrvxp1q58dn57t unique (email)

alter table if exists member
    add constraint UK_4rebv7u7h123c0kvaq3jv89ym unique (employee_id)

alter table if exists refresh_token
    add constraint UK_dnbbikqdsc2r2cee1afysqfk9 unique (member_id)