name: Deploy To oracle_serverA_front

on:
  push:
    branches:
      - front_dev
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository file 불러오기 
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install packages        
        run: cd /home/runner/work/OneGo/onego-front/ && npm install
        
      - name: Build Vue application
        run: npm run build
